apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    domain: app
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: app
  template:
    metadata:
      name: app-template
      labels:
        domain: app
    spec:
      containers:
      - name: app-image
        image: {{ Values.image | default Values.image }}
        imagePullPolicy: Always
        ports:
        - name: app-pod-port
          containerPort: 8000
          protocol: TCP
        env:
        - name: DB_USER
          value: {{ .Values.user }}
        - name: DB_NAME
          value: {{ .Values.name }}
        - name: DB_PASSWORD
          value: {{ .Values.password }}
        - name: DB_HOST
          value: {{ .Values.host }}
        - name: DB_PORT
          value: {{ .Values.port }}